name: flutter_web_intercom_sample
description: Intercom integration on Flutter web.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  js: ^0.7.1
  visibility_detector: ^0.4.0+2

flutter:
  uses-material-design: true